# Generated by Django 4.0.1 on 2022-01-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='odometer_reading',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='distance_travelled',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rentalrate',
            name='extra_charge_per_km',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
