# Generated by Django 4.0.1 on 2022-01-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_name',
            field=models.CharField(default=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(default=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='reg_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
