# Generated by Django 4.0.1 on 2022-02-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_address_address_name_branch_branch_name_car_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='booked_at',
            field=models.DateTimeField(),
        ),
    ]
